# Generated by Django 5.2.7 on 2025-10-29 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'قيد المعالجة'), ('approved', 'موافق'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('from_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_transfers', to='core.gradelevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('to_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_transfers', to='core.gradelevel')),
            ],
        ),
    ]
