# Generated by Django 5.2.7 on 2025-10-29 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_grades', to='core.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.gradelevel'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.gradelevel'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.teacher'),
        ),
    ]
