# Generated by Django 5.2.7 on 2025-10-30 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-date'], 'verbose_name': 'امتحان', 'verbose_name_plural': 'الامتحانات'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'درجة', 'verbose_name_plural': 'الدرجات'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-date', 'title'], 'verbose_name': 'درس', 'verbose_name_plural': 'دروس'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'مادة', 'verbose_name_plural': 'المواد'},
        ),
        migrations.AlterModelOptions(
            name='timetableslot',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': 'حصة', 'verbose_name_plural': 'الجدول الدراسي'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(verbose_name='تاريخ الامتحان'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject', verbose_name='المادة'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان الامتحان'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.exam', verbose_name='الامتحان'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الدرجة'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_grades', to='core.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='materials',
            field=models.FileField(blank=True, null=True, upload_to='materials/', verbose_name='مرفقات'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academics.subject', verbose_name='المادة'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان الدرس'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='فيديو'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.gradelevel', verbose_name='الصف'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المادة'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.teacher', verbose_name='المعلم'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='end_time',
            field=models.TimeField(verbose_name='وقت الانتهاء'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.gradelevel', verbose_name='الصف'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='start_time',
            field=models.TimeField(verbose_name='وقت البدء'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.subject', verbose_name='المادة'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.teacher', verbose_name='المعلم'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'الأحد'), (1, 'الاثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس'), (5, 'الجمعة'), (6, 'السبت')], verbose_name='اليوم'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('exam', 'student')},
        ),
    ]
