# Generated by Django 5.2.7 on 2025-11-05 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_exam_options_alter_grade_options_and_more'),
        ('core', '0005_alter_gradelevel_options_alter_manager_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.teacher', verbose_name='المعلم'),
        ),
    ]
