# Generated by Django 5.2.7 on 2025-11-05 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_subject_teacher'),
        ('core', '0006_alter_user_national_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['subject', 'unit', 'order', 'title'], 'verbose_name': 'درس', 'verbose_name_plural': 'دروس'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='materials',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('نظري', 'نظري'), ('عملي', 'عملي'), ('شفوي', 'شفوي')], default='نظري', max_length=50, verbose_name='نوع الامتحان'),
        ),
        migrations.AddField(
            model_name='exam',
            name='section',
            field=models.CharField(blank=True, max_length=5, verbose_name='الشعبة'),
        ),
        migrations.AddField(
            model_name='grade',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher', verbose_name='قيم الدرجات'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='رقم الدرس'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.CharField(blank=True, max_length=100, verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.CharField(blank=True, max_length=5, verbose_name='الشعبة'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='room',
            field=models.CharField(blank=True, max_length=50, verbose_name='الغرفة'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='section',
            field=models.CharField(blank=True, max_length=5, verbose_name='الشعبة'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'grade', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together={('grade', 'section', 'weekday', 'start_time')},
        ),
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='materials/', verbose_name='مرفق')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academics.lesson', verbose_name='الدرس')),
            ],
            options={
                'verbose_name': 'مرفق درس',
                'verbose_name_plural': 'مرفقات الدرس',
            },
        ),
    ]
