# Generated by Django 5.2.7 on 2025-11-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_lesson_options_remove_lesson_materials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الفيديو'),
        ),
    ]
