# Generated by Django 5.2.7 on 2025-10-30 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradelevel',
            options={'ordering': ['year', 'name'], 'verbose_name': 'مرحلة/صف', 'verbose_name_plural': 'المراحل/الصفوف'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'طالب', 'verbose_name_plural': 'الطلاب'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'معلم', 'verbose_name_plural': 'المعلمون'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الصف'),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='year',
            field=models.IntegerField(verbose_name='السنة الدراسية'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.gradelevel', verbose_name='الصف'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(default='A', max_length=10, verbose_name='الشعبة/الفصل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='مستخدم'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, verbose_name='تخصص'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='مستخدم'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(help_text='الرقم الوطني للمستخدم', max_length=20, unique=True, verbose_name='الرقم الوطني'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'طالب'), ('teacher', 'معلم'), ('admin', 'مسؤول')], default='student', max_length=10, verbose_name='الدور'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('user',)},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['national_id'], name='core_user_nationa_be760e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='core_user_usernam_e8adca_idx'),
        ),
    ]
