# Generated by Django 5.2.7 on 2025-10-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_gradelevel_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='صورة الملف الشخصي'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='الرقم الوطني'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'طالب'), ('teacher', 'معلم'), ('manager', 'مدير المدرسة')], default='student', max_length=10, verbose_name='الدور'),
        ),
    ]
