# Generated by Django 5.2.7 on 2025-11-04 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_phone_user_middle_name_user_third_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradelevel',
            options={'verbose_name': 'صف', 'verbose_name_plural': 'الصفوف'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='core_user_usernam_e8adca_idx',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='middle_name',
            new_name='second_name',
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='gradelevel',
            name='year',
        ),
        migrations.AddField(
            model_name='user',
            name='fourth_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='الاسم الرابع'),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='اسم الصف'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='office',
            field=models.CharField(blank=True, max_length=100, verbose_name='المكتب'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gradelevel', verbose_name='الصف'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(default='A', max_length=10, verbose_name='الشعبة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='الاسم الأول'),
        ),
    ]
